#!/system/bin/sh

COMMAND="$1"
SDK=$(getprop ro.build.version.sdk)
GLOBAL_KEY="database"

fetch_target_info() {
    local PKG="$1"
    pm list packages | grep -qw "package:$PKG" || return 1
    dumpsys package "$PKG" | sed -n 's/.*userId=\([0-9]*\).*/\1/p' | head -n 1
}

sync_registry() {
    local TARGET_PKG="$1"
    local MODE="$2"
    local CURRENT_RAW=$(settings get global "$GLOBAL_KEY" | sed 's/null//')
    local REBUILT_DATA=""
    local OLD_IFS="$IFS"
    IFS=','
    for entry in $CURRENT_RAW; do
        [ -z "$entry" ] && continue
        
        local ITEM_PKG=$(echo "$entry" | cut -d'=' -f1)
        local ITEM_MODE=$(echo "$entry" | cut -d'=' -f2)
        if pm list packages | grep -qw "package:$ITEM_PKG" && [ "$ITEM_PKG" != "$TARGET_PKG" ]; then
            REBUILT_DATA="${REBUILT_DATA}${ITEM_PKG}=${ITEM_MODE},"
        fi
    done
    IFS="$OLD_IFS"
    if [ ! -z "$TARGET_PKG" ] && [ ! -z "$MODE" ]; then
        REBUILT_DATA="${REBUILT_DATA}${TARGET_PKG}=${MODE},"
    fi

    local FINAL_DATA=$(echo "$REBUILT_DATA" | sed 's/,$//')
    settings put global "$GLOBAL_KEY" "$FINAL_DATA"
    echo "$FINAL_DATA"
}

run_mode() {
    local MODE="$1"
    local PKG="$2"

    [ -z "$MODE" ] || [ -z "$PKG" ] && { echo "Error: missing arguments!"; return 1; }    
    local NEW_DATA=$(sync_registry "$PKG" "$MODE")
    local UID=$(fetch_target_info "$PKG")
    [ -z "$UID" ] && { echo "Error: Package '$PKG' not found in device!"; return 1; }
    local PKG_LIST=$(echo "$NEW_DATA" | tr ',' '\n' | grep "=" | cut -d'=' -f1 | paste -sd ",")

    check_and_lock() {
        local TARGET_MODE="$1" TARGET_PKG="$2"
        local L_PATH="/data/local/tmp/bin/.locks/${TARGET_PKG}.lock"
        [ ! -d "/data/local/tmp/bin/.locks" ] && mkdir -p "/data/local/tmp/bin/.locks"
        
        if [ ! -f "$L_PATH" ] || [ "$(cat "$L_PATH")" != "$TARGET_MODE" ]; then
            echo "$TARGET_MODE" > "$L_PATH"
            return 0
        fi
        return 1
    }

    case "$MODE" in
        "standart"|"1")
            check_and_lock "standart" "$PKG" && {
                cmd package reconcile-secondary-dex-files "$PKG" /dev/null 2>&1
                cmd package compile -m speed-profile -f "$PKG" >/dev/null 2>&1
                for opt in RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND WAKE_LOCK; do
                    cmd appops set "$PKG" "$opt" default >/dev/null 2>&1
                done
                cmd activity set-standby-bucket "$PKG" working_set >/dev/null 2>&1
                cmd netpolicy remove restrict-background-whitelist "$UID" >/dev/null 2>&1
                cmd netpolicy remove restrict-background-blacklist "$UID" >/dev/null 2>&1
                cmd deviceidle whitelist -"$PKG" >/dev/null 2>&1
            }
            cmd activity set-inactive "$PKG" true >/dev/null 2>&1
            cmd thermalservice override-status 1 >/dev/null 2>&1
            cmd power set-fixed-performance-mode-enabled false >/dev/null 2>&1
            cmd power set-adaptive-power-saver-enabled false >/dev/null 2>&1
            cmd set-mode 1 >/dev/null 2>&1
            ;;
        "performance"|"2")
            check_and_lock "performance" "$PKG" && {
                cmd package reconcile-secondary-dex-files "$PKG" /dev/null 2>&1
                cmd package compile -m speed -f "$PKG" >/dev/null 2>&1
                cmd package compile --compile-layouts --secondary-dex -f "$PKG" >/dev/null 2>&1
                for opt in RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND WAKE_LOCK; do
                    cmd appops set "$PKG" "$opt" allow >/dev/null 2>&1
                done
                cmd activity set-standby-bucket "$PKG" active >/dev/null 2>&1
                cmd netpolicy add restrict-background-whitelist "$UID" >/dev/null 2>&1
                cmd netpolicy remove restrict-background-blacklist "$UID" >/dev/null 2>&1
                cmd deviceidle whitelist +"$PKG" >/dev/null 2>&1
                
                TARGET_PROP="game_driver_opt_in_apps"
                [ "$SDK" -ge 31 ] && TARGET_PROP="updatable_driver_production_opt_in_apps"
                settings put global "$TARGET_PROP" "$PKG_LIST"
                settings put global "${TARGET_PROP%_in_apps}_out_apps" 1
            }
            cmd activity set-inactive "$PKG" false >/dev/null 2>&1
            cmd power set-fixed-performance-mode-enabled true >/dev/null 2>&1
            cmd power set-adaptive-power-saver-enabled false >/dev/null 2>&1
            cmd set-mode 0 >/dev/null 2>&1
            ;;
        "battery"|"3")
            check_and_lock "battery" "$PKG" && {
                cmd package compile -m verify -f "$PKG" >/dev/null 2>&1
                for opt in RUN_IN_BACKGROUND RUN_ANY_IN_BACKGROUND WAKE_LOCK; do
                    cmd appops set "$PKG" "$opt" ignore >/dev/null 2>&1
                done
                cmd activity set-standby-bucket "$PKG" rare >/dev/null 2>&1
                cmd netpolicy remove restrict-background-whitelist "$UID" >/dev/null 2>&1
                cmd netpolicy add restrict-background-blacklist "$UID" >/dev/null 2>&1
                cmd deviceidle whitelist -"$PKG" >/dev/null 2>&1
            }
            cmd activity set-inactive "$PKG" true >/dev/null 2>&1
            cmd thermalservice override-status 1 >/dev/null 2>&1
            cmd power set-fixed-performance-mode-enabled false >/dev/null 2>&1
            cmd power set-adaptive-power-saver-enabled true >/dev/null 2>&1
            cmd set-mode 1 >/dev/null 2>&1
            ;;
        *)
            echo "Unknown mode $MODE!, Please usage [1|2|3|standart|performance|battery]"
            return 1
            ;;
    esac
    echo "Success"
}

# --- INTERFACE COMMANDS ---
case "$COMMAND" in
    "set-mode"|"-m")
        run_mode "$2" "$3"
        ;;
    "get-mode"|"-g")
        [ -z "$2" ] && echo "Error: missing package name!" && exit 1
        CLEAN_DB=$(sync_registry "" "")
        RESULT=$(echo "$CLEAN_DB" | grep -o "$2=[^,]*" | cut -d'=' -f2)
        [ -z "$RESULT" ] && echo "No profil for $2" || echo "$2: $RESULT"
        ;;
    "list-apps"|"-l")
        echo "Optimized Packages:"
        RAW_DB=$(sync_registry "" "")
        if [ -z "$RAW_DB" ]; then 
            echo "  (None)"
        else
            echo "$RAW_DB" | tr ',' '\n' | grep "=" | while read -r entry; do
                echo "- ${entry%=*} [${entry#*=}]"
            done
        fi
        ;;
    "help"|"-help"|"")
        echo "Game Opt Manager (gameopt) commands:"
        echo "  help"
        echo "      Print this help text."
        echo ""
        echo "  set-mode [-m MODE] [1|2|3|standart|performance|battery] <PACKAGE_NAME>"
        echo "    Changes the performance profile for a specific package."
        echo "    Mode must be one of:"
        echo "      standart:   Standart performance and power consumption."
        echo "      performance: Advanced performance for gaming."
        echo "      battery:   Power saving mode to extend battery life."
        echo ""
        echo "  get-mode | -g <PACKAGE_NAME>"
        echo "    Display the current optimization mode for the package."
        echo ""
        echo "  list-apps | -l"
        echo "    Show all packages currently optimized by pkgopt."
        echo ""
        ;;
    *)
        echo "Unknown gameopt command: $1"
        ;;
esac
